colors:
- [90, 211, 41]
- [248, 231, 28]
- [155, 155, 155]
- [208, 2, 27]
names: [electric_scooter, brailleblock, crosswalk, fireplug]
nc: 4
train: ../144209_electric_scooter(new shapes) (with train-val tags)/images/train
val: ../144209_electric_scooter(new shapes) (with train-val tags)/images/val
